export const LOGIN = '/'
export const STUDENT = '/student'
export const TEACHER = '/teacher'
export const ADMIN = '/admin'
export const MENTEES = '/teacher/mentees'
export const STUDENTS = '/teacher/students'